### PR TITLE
Add components for the synthesis recipe app

### PR DESCRIPTION
**Pull request by hhaoyan**
@codytodonnell Opening a temporary PR here.

One thing that I'd like to have is to hide the periodic table for the top search bar, since I'm just using it for text query. Currently I'm doing it by setting `hidePeriodicTable=true` in `SearchUISearchBar` but I have no control via `SearchUI` component. Let me know if there is indeed an option and I did not see it...

### CODE REVIEW

**Comment by codytodonnell** [comment]
You're right there was not a way to control that on the `SearchUI` level. I just pushed a change that should handle this.

You can now set `searchBarPeriodicTableMode={PeriodicTableMode.NONE}` on the `SearchUI` component where `PeriodicTableMode` is an enum of allowed values.

See https://github.com/materialsproject/mp-react-components/commit/8cdfabb7b6a3b92d64269d10f14c9b98fbce7178

**Comment by codytodonnell** [comment]
@hhaoyan I just merged in a change that should solve our styling problem.

See https://github.com/materialsproject/mp-react-components/pull/459. Let me know if that makes sense.

**Comment by hhaoyan** [comment]
This works. Thanks!

**Comment by hhaoyan** [comment]
Hey Cody! I'm almost done with the frontend of synthesis recipe app and hope if you could help me with two more items:

1. Sorting probably isn't very much meaningful (as many properties are not single-valued) so I'm thinking to remove the sorting dropdown button.
2. The "Columns" button isn't relevant to a card-based display so maybe removing it seems a better option.

That's the only thing remaining to be done for the synthesis recipes app! Could you help me implement the option to hide "columns" and "sorting"? After that I think we could merge this PR into the main code repo and try to publish this new app :) (the backend and database stuff are as ready as the frontend.)

**Comment by codytodonnell** [comment]
Great! I will test this out this afternoon.

Just merged in some changes to address the 2 issues you mentioned: https://github.com/materialsproject/mp-react-components/pull/463

**Pull request merged**
